Removed `--no-plugins` from composer installation: needed to install PHPCS rulesets
Should fix:

```
Run docker run --rm --entrypoint=php ghcr.io/roave/docbooktool:test-image vendor/bin/phpcs
ERROR: Referenced sniff "Doctrine" does not exist

Run "phpcs --help" for usage information

Error: Process completed with exit code 3.
```

Ref: https://blog.packagist.com/composer-2-7-and-cve-2024-24821/
Ref: https://getcomposer.org/changelog/2.7.0